### ISSUE TITLE
POST数组，数据丢失

### ISSUE THREAD

**Issue by mirror222** [beetlex-io/FastHttpApi#147]
var myList=[];

myList.push('xxxxx');
myList.push('BBBB');
$.post("/api/XXXXXXX", {myList}, function(result){
	console.log("log");
  });

context.Data 获取只能获取 xxxx 而已，BBB丢失了。
是否我没有正确使用？

**Comment by IKende** [comment]
`FormUrlData`这一块解释针对数组是可能存在问题，建议client先拼接成一个string.
打包一个sample提交上来我测一下

**Comment by mirror222** [comment]
> FormUrlData

请问哪里有FormUrlData相关的资料吗？ 我没有找到

**Comment by IKende** [comment]
这是默认HTTP的几种提交格式之一，组件都可以定义这些转换标签，参考
https://github.com/IKende/FastHttpApi/blob/master/src/Data/DataConvertAttribute.cs

**Comment by mirror222** [comment]
`
        [Post(Route = "/api/SaveUserOptions")]
        [FormUrlDataConvert]
        public JsonResult SaveUserOptions(IHttpContext context, object myList)
        {

            var code = 0;
            var msg = "ok";

            var json = GetJsonResult(code, msg, "");
           
            return json;
        }`

我这样获取不到数据。
或者有例子吗。。。感谢

**Comment by IKende** [comment]
如果没有特别的需求，建议用json提交，然后参数设置成string[] body
