### ISSUE TITLE
请问BeetleX.Http.Clients怎么设置连接超时时间

### ISSUE THREAD

**Issue by yuchunhang** [beetlex-io/FastHttpApi#148]
目标主机域名挂了，设置httpClusterApi.TimeOut = 3000;但是还是会等待几十秒左右。
是否有地方可以设置连接超时时间？

**Comment by IKende** [comment]
这个timeout只适合请求响应超时，对于tcp connect超时暂不提供设置

**Comment by yuchunhang** [comment]
多谢，我了解了。
顺便问一下，后续是否有这个功能的支持呢？

**Comment by IKende** [comment]
这个需要在Beetlex的基础中才能添加，行标记一下。
按理httpClusterApi应该会优先使用通了的地址才对。
