### ISSUE TITLE
突然多了很多warning日志

### ISSUE THREAD

**Issue by yintao666** [beetlex-io/FastHttpApi#150]
项目升级到netcore 3.0之后,今天看服务器日志发现突然多了很多,大佬知道是什么引发的吗?

2020/11/10 23:22:52	Warring	SYSTEM	[::ffff:127.0.0.1]:50756 send data completed socket error Success Object reference not set to an instance of an object.@   at BeetleX.TcpServer.SendCompleted(SocketAsyncEventArgs e)
2020/11/10 23:22:54	Warring	SYSTEM	[::ffff:127.0.0.1]:50762 send data completed socket error Success Object reference not set to an instance of an object.@   at BeetleX.TcpServer.SendCompleted(SocketAsyncEventArgs e)

**Comment by IKende** [comment]
Warring 不影响服务处理，这情况是数据发送完成后处理会话状态时因连接关闭引起。

**Comment by yintao666** [comment]
emmm 可是服务器一开着  只要有访问就会出warning日志...
