### ISSUE TITLE
winfrom wpf webApi 运行报错

### ISSUE THREAD

**Issue by qq1078350533** [beetlex-io/FastHttpApi#151]
BeetleX.FastHttpApi.HttpApiServer.ResolveHandler(Object sender, ResolveEventArgs args)

**Comment by beetlex-io** [comment]
这个过程会报加载不了程序集的警告，正常影响工作。

**Comment by qq1078350533** [comment]
我要 怎么做才能不报错呢 就是按官网的例子 编译的 exe 正常

**Comment by beetlex-io** [comment]
主要是IDE在调式阶段会定位这个异常，实际编译发布于会被catch，不会影响程序运行。
