### ISSUE TITLE
websocket没有断开事件

### ISSUE THREAD

**Issue by qq1078350533** [beetlex-io/FastHttpApi#152]
websocket没有断开事件 我想在断开事件里处理点事情 但发现 并没有断开事件 只有 WebSocketConnect WebSocketReceive 我试着重写了Disconnect 但还是没有触发websocket的断开事件

**Comment by beetlex-io** [comment]
是client还是server?

**Comment by qq1078350533** [comment]
> 是client还是server?

server 啊 创建websocket服务器 客户端断开 事件 我服务器 要处理事情呢

**Comment by beetlex-io** [comment]
HttpDisconnect事件
HttpToken token = (HttpToken)e.Session.Tag;
token有websocket属性判断
