### ISSUE TITLE
Web请求阻塞

### ISSUE THREAD

**Issue by microfu** [beetlex-io/FastHttpApi#153]
您好！此问题影响开发，请给出技术指导。
问题：偶尔会出现Web请求阻塞这种情况。这会导致整个Web应用功能不可用。但是，可通过启动的命令行，手动“Ctrl + C”键中止，又恢复继续响应，并输出之前的请求结果。日志关闭也无效。

BeetleX.FastHttpApi: 1.9.3.12;
Beetlex.FastHttpApi.Hosting: 1.3.4.2

盼复！

**Comment by beetlex-io** [comment]
这个我也无法查明原因，估计是不同windows系统对控制台接管的问题，用nssm把程序转成winservice运行试下，
我一直用这个在windows运行。

**Comment by microfu** [comment]
感谢回复。
Linux有出现过这种情况么？或者，你的Windows有出现过上述情况么？
目前，我们在Windows或Linux都有部署这套框架。

**Comment by beetlex-io** [comment]
Linux下还没碰到这情况，windows在win10和2016这些系统上有出现过这情况，nssm部署服务没出现过这情况

**Comment by microfu** [comment]
是的。目前就是在Windows 10和云上的Win 2016出现过，而且几乎每天都会发生。
Linux下的Docker中目前来看，没有出现过。当然，还得等反馈。
不过，这个框架还是不错的！
