### ISSUE TITLE
指定配置文件的路径

### ISSUE THREAD

**Issue by mirror222** [beetlex-io/FastHttpApi#156]
我现在的办法是启动的时候用代码从配置文件加载HttpOptions，然后 new HttpApiServer(options); 来初始化，但问题来了。
如果我调用  context.Server.SaveOptions(); 会发现配置文件还是保存在程序所在的目录。

请问如何指定配置文件的路径呢？ 感谢。

**Comment by beetlex-io** [comment]
是不支持保存到其他目录，你可以自己用json序列和反序化HttpOptions，这样就可以自己定义保存方式。
