### ISSUE TITLE
跨域问题，全局设置跨域，但是部分接口跨域成功 部分接口报错

### ISSUE THREAD

**Issue by RichardsATcn** [beetlex-io/FastHttpApi#158]
FastHttpApi 1.9.5  FastHttpApi.jwt 0.7.5.3
main代码行

 HttpApiServer server = new HttpApiServer();
            server.Options.SetDebug();
            server.Options.CrossDomain = new OptionsAttribute { AllowOrigin = "*", AllowMethods = "*", AllowHeaders = "*", AllowMaxAge = "*" };
            server.Options.Port = ServerPort;
            server.Options.ManageApiEnabled = true;
            server.Options.LogLevel = BeetleX.EventArgs.LogType.Info;
            server.Options.LogToConsole = true;
   server.AddExts("woff;ttf");
            server.UseApiDoc();
            server.UseJWT();

            server.Open();
            //注册webapi控制器
            server.Register(typeof(Program).Assembly);
、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、、
前端测试代码： 
前端从 192.168.33.122:5500端口开启网页调用 9898的FastHttpApi后端
     clickMe: function () {
          var obj = this;
          axios.post('http://192.168.33.122:9898/student/login', {
            "username": "123",
            "password": "123456"
          }).then(function (response) {
            console.log(response);
            obj.token = response.data.Data.Data.token
          });
        },
        clickMe1: function () {
          var obj = this;
          console.log(obj.token)
          axios.post('http://192.168.33.122:9898/train/mgr/pullMsgList', {
             "user": "学生1",
            "user_type": "学生",
          "train_role": "",
          "access_type": "APP",
             "temporary_data": {
               "item": "测试参数JSON,用于存放app端的临时数据"
          }},{header:{"Authorization": obj.token}}).then(function (response) {
            console.log(response);
            obj.token = response.data.Data.Data.token
          });
        },
///////////////////////////////////////////////////////////////////////////////////////
第一个接口 成功返回
{data: {…}, status: 200, statusText: "OK", headers: {…}, config: {…}, …}
第二个接口报错
Access to XMLHttpRequest at 'http://192.168.33.122:9898/train/mgr/pullMsgList' from origin 'http://192.168.33.122:5500' has been blocked by CORS policy: Request header field content-type is not allowed by Access-Control-Allow-Headers in preflight response.

isAxiosError.js:10 POST http://192.168.33.122:9898/train/mgr/pullMsgList net::ERR_FAILED
(anonymous) @ isAxiosError.js:10
e.exports @ isAxiosError.js:10
e.exports @ isAxiosError.js:10
Promise.then (async)
r.request @ isAxiosError.js:10
r.<computed> @ isAxiosError.js:10
(anonymous) @ isAxiosError.js:10
clickMe1 @ index.html:48
click @ VM336:3
invokeWithErrorHandling @ vue.js:1872
invoker @ vue.js:2197
original._wrapper @ vue.js:7591

isAxiosError.js:10 Uncaught (in promise) Error: Network Error
    at e.exports (isAxiosError.js:10)
    at XMLHttpRequest.l.onerror (isAxiosError.js:10)
e.exports @ isAxiosError.js:10
l.onerror @ isAxiosError.js:10
Promise.then (async)
clickMe1 @ index.html:55
click @ VM336:3
invokeWithErrorHandling @ vue.js:1872
invoker @ vue.js:2197
original._wrapper @ vue.js:7591

**Comment by RichardsATcn** [comment]
[BeetleX.Samples.Webapi.JWT (1).zip](https://github.com/beetlex-io/FastHttpApi/files/6614279/BeetleX.Samples.Webapi.JWT.1.zip)

使用实例 JWT 和 跨域例子 混合起来 也会有同样的现象

**Comment by RichardsATcn** [comment]
多谢大佬回复，我后面调试已经发现了 前端 header代码的问题
现在使用 vue axios  clickMe 登陆ok，但是还是同样的现象。浏览器中测试请求已经带有Token了
![微信图片_20210608195619](https://user-images.githubusercontent.com/8119891/121181252-616a3f00-c894-11eb-8e08-fdc89dae7b04.png)


`<html>
<head>
  <meta charset="utf-8">
  <title>VueTest</title>
  <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>
  <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
</head>
<body>
  <div id="app">
    <div>
      <button v-on:click="clickMe()">登录</button>
    </div>
    <div>
      <button v-on:click="clickMe1()">测试</button>
    </div>
    <div v-for="(value,key) in helloData">
      {{ key }} : {{ value }}
    </div>
  </div>
  <script>
    var app = new Vue({
      el: '#app',
      data: {
        helloData: {},
        token: null
      },
      methods: {
        clickMe: function () {
          var obj = this;
          axios.post('http://127.0.0.1/Login', {
            "name": "100123",
            "pwd": "123456"
          }).then(function (response) {
            console.log(response);
            obj.token = response.data.Data
          });
        },
        clickMe1: function () {
          var obj = this;
          console.log("token",obj.token)

          axios({
            method: 'post',            
            url: 'http://127.0.0.1/ListEmployee',
            headers:{"Authorization": obj.token,'Content-Type': 'application/json'}            
          }).then(function (response) {
            console.log(response);
            obj.token = response.data.Data.Data.token
          });
        },
      }
    })
  </script>
</body>
</html>`


`namespace BeetleX.Samples.Webapi.JWT
{
    class Program
    {
        static void Main(string[] args)
        {
            HttpApiServer server = new HttpApiServer();
            server.Options.SetDebug();
            server.Options.Port = 80;
            server.Options.LogLevel = EventArgs.LogType.Info;
            server.Options.LogToConsole = true;
//            server.Options.SSL = true;
//            server.Options.CertificateFile = "ssl.pfx";
//            server.Options.CertificatePassword = "123456"; 
            server.Options.CrossDomain = new OptionsAttribute { AllowOrigin = "*", AllowMethods = "*" , AllowHeaders = "*"};
           server.UseJWT();
            server.Register(typeof(Program).Assembly);
            server.Open();
            System.Threading.Thread.Sleep(-1);
        }
    }
}
`


`using BeetleX.FastHttpApi;
using BeetleX.FastHttpApi.Jwt;

namespace BeetleX.Samples.Webapi.JWT
{
    [Controller]
    class Webapi
    {
        [AuthMark(AuthMarkType.Admin)]
        public object ListEmployee(string jwt_user, string jwt_role, IHttpContext context)
        {
            context.Server.Log(EventArgs.LogType.Warring, context.Session, $"{jwt_user}[{jwt_role}]");
            return Northwind.Data.DataHelper.Defalut.Employees;
        }
        [AuthMark(AuthMarkType.NoValidation)]
        public object List(string jwt_user, string jwt_role, IHttpContext context)
        {
            context.Server.Log(EventArgs.LogType.Warring, context.Session, $"{jwt_user}[{jwt_role}]");
            return Northwind.Data.DataHelper.Defalut.Customers;
        }
        [AuthMark(AuthMarkType.NoValidation)]
        public string Login(string name, string pwd, IHttpContext context)
        {
            string result;
            if (name == "admin")
            {
                result = context.SetAdminJwtToken(name);
            }
            else
            {
                result = context.SetJwtToken(name, "user");
            }
            return result;
        }
    }
}
`

**Comment by beetlex-io** [comment]
[AuthMark(AuthMarkType.Admin)]说明必须是admin角色，其他角色也是不通过的，可以使用其他选项。
控制台有日志，如果是401说明token不存在或和AuthMarkType不匹配

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: ***@***.***>
发送时间: 2021年6月8日 20:03
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [beetlex-io/FastHttpApi] 跨域问题，全局设置跨域，但是部分接口跨域成功 部分接口报错 (#158)


多谢大佬回复，我后面调试已经发现了 前端 header代码的问题
现在使用 vue axios clickMe 登陆ok，但是还是同样的现象。浏览器中测试请求已经带有Token了
[微信图片_20210608195619]<https://user-images.githubusercontent.com/8119891/121181252-616a3f00-c894-11eb-8e08-fdc89dae7b04.png>

`
<title>VueTest</title> <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script> <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
登录
测试
{{ key }} : {{ value }}
<script> var app = new Vue({ el: '#app', data: { helloData: {}, token: null }, methods: { clickMe: function () { var obj = this; axios.post('http://127.0.0.1/Login', { "name": "100123", "pwd": "123456" }).then(function (response) { console.log(response); obj.token = response.data.Data }); }, clickMe1: function () { var obj = this; console.log("token",obj.token)

      axios({



        method: 'post',



        url: 'http://127.0.0.1/ListEmployee',



        headers:{"Authorization": obj.token,'Content-Type': 'application/json'}



      }).then(function (response) {



        console.log(response);



        obj.token = response.data.Data.Data.token



      });



    },



  }



})


</script> `

namespace BeetleX.Samples.Webapi.JWT { class Program { static void Main(string[] args) { HttpApiServer server = new HttpApiServer(); server.Options.SetDebug(); server.Options.Port = 80; server.Options.LogLevel = EventArgs.LogType.Info; server.Options.LogToConsole = true; // server.Options.SSL = true; // server.Options.CertificateFile = "ssl.pfx"; // server.Options.CertificatePassword = "123456"; server.Options.CrossDomain = new OptionsAttribute { AllowOrigin = "*", AllowMethods = "*" , AllowHeaders = "*"}; server.UseJWT(); server.Register(typeof(Program).Assembly); server.Open(); System.Threading.Thread.Sleep(-1); } } }

`using BeetleX.FastHttpApi;
using BeetleX.FastHttpApi.Jwt;

namespace BeetleX.Samples.Webapi.JWT
{
[Controller]
class Webapi
{
[AuthMark(AuthMarkType.Admin)]
public object ListEmployee(string jwt_user, string jwt_role, IHttpContext context)
{
context.Server.Log(EventArgs.LogType.Warring, context.Session, $"{jwt_user}[{jwt_role}]");
return Northwind.Data.DataHelper.Defalut.Employees;
}
[AuthMark(AuthMarkType.NoValidation)]
public object List(string jwt_user, string jwt_role, IHttpContext context)
{
context.Server.Log(EventArgs.LogType.Warring, context.Session, $"{jwt_user}[{jwt_role}]");
return Northwind.Data.DataHelper.Defalut.Customers;
}
[AuthMark(AuthMarkType.NoValidation)]
public string Login(string name, string pwd, IHttpContext context)
{
string result;
if (name == "admin")
{
result = context.SetAdminJwtToken(name);
}
else
{
result = context.SetJwtToken(name, "user");
}
return result;
}
}
}
`

―

**Comment by RichardsATcn** [comment]
多谢大佬，看到提示是说得对跨域问题，把自己绕进去了  多谢
