### ISSUE TITLE
请问怎么接入swagger

### ISSUE THREAD

**Issue by christan-duplicate** [beetlex-io/FastHttpApi#162]
请问怎么接入swagger

**Comment by beetlex-io** [comment]
组件并没有提供这插件，不过可以自己扩展
1）了解swagger对应的json结构
2）通过HttpApiServer.ActionFactory.ActionHandler信息生成相应的json结构文件。

**Comment by christan-duplicate** [comment]
> 组件并没有提供这插件，不过可以自己扩展
> 1）了解swagger对应的json结构
> 2）通过HttpApiServer.ActionFactory.Handlers信息生成相应的json结构文件。

那工程有点大
