### ISSUE TITLE
nuget中fasthttpapi版本 

### ISSUE THREAD

**Issue by hugeng1979** [beetlex-io/FastHttpApi#166]
从nuget中下载了最新版本 2.0.8     <PackageReference Include="BeetleX.FastHttpApi" Version="2.0.8" 
发现原来的代码有报错了，类HttpApiServer 下的Log方法只剩下下面几个
  public override void Log(IServer server, ServerLogEventArgs e);
        public void Log(LogType type, ISession session, string message);
        public void Log(LogType type, ISession session, object tag, string message);

而在此github下的源代码，fasthttpapi最新版本是1.8.2.7
在文件 https://github.com/beetlex-io/FastHttpApi/blob/master/src/HttpApiServer.cs
是有此方法
public void Log(LogType type, string message)

请问，我能用nuget里的最新版本吗？还是要选择哪个指定版本更合适？

**Comment by beetlex-io** [comment]
建议用新版本，然后调整一下日志调用的方法

**Comment by hugeng1979** [comment]
能给个具体的调用例子吗？ ISession填什么参数？有没有最新版本的相关文档访问地址？谢谢。

**Comment by beetlex-io** [comment]
可以通过ihttpcontext得到，这个参数也可以为空
