### ISSUE TITLE
NET6 静态资源慢

### ISSUE THREAD

**Issue by Haku-Men** [beetlex-io/FastHttpApi#167]
按照教程在views放置静态资源，在NET6下访问很慢，但是能读取到

**Comment by beetlex-io** [comment]
看情况是gzip处理上不兼容

**Comment by beetlex-io** [comment]
NET6 重新调整了GzipStream.Flush方法的实现，导致无法兼容
https://github.com/dotnet/runtime/pull/43834/commits/af13fb940b6521e83c1551cb21442f1b116e2b5e#diff-a076647d6d5119e4e3b482835f098318b585fc7fd9cb16116c45395721c61c3dR531-R533

**Comment by beetlex-io** [comment]
Fixed 2.1.0

**Comment by Haku-Men** [comment]
已更新测试没问题
