### ISSUE TITLE
有计划支持net6.0 吗

### ISSUE THREAD

**Issue by nodyang** [beetlex-io/FastHttpApi#168]
FastHttpApi  
FastHttpApi.Hosting 好像已经不配套了

**Comment by beetlex-io** [comment]
如果是使用net6，必须使用最新版本的FastHttpApi，低版本在net6下的gzip会出错。FastHttpApi.Hosting 是兼容新版本的FastHttpApi。

下一版本会发布beetlex和FastHttpApi的net6版本

**Comment by nodyang** [comment]
好来。尽情期待
