### ISSUE TITLE
.net framework 4.8希望使用fasthttpapi 接入静态资源，请问该使用哪个版本

### ISSUE THREAD

**Issue by memoryrobber** [beetlex-io/FastHttpApi#169]
好像没有支持静态资源的，并且适配net standard ,只找到1.5.6.6版本，api是支持，不支持静态文件

**Comment by beetlex-io** [comment]
可以下载这个https://www.nuget.org/packages/BeetleX.FastHttpApi.std2/
由于.net5后支持独立部署，所以后续的版本不再考虑支持std
