### ISSUE TITLE
关于注入问题的疑问

### ISSUE THREAD

**Issue by nodyang** [beetlex-io/FastHttpApi#172]
![image](https://user-images.githubusercontent.com/3090191/158766511-d46d8130-696c-447d-b365-2dd312729e30.png)
![image](https://user-images.githubusercontent.com/3090191/158766640-08e08c55-2db6-4c29-ba45-e0ab4965d53f.png)

  services.AddSingleton<IBackgroundRunService, BackgroundRunService>(); 
  理论上我的 BackgroundService 和 FastHttpApi controller  对IBackgroundRunService 的持有 应该是同一个对象  但测试效果好像不是
  微软的 mvc api 是可以的  求解    
![image](https://user-images.githubusercontent.com/3090191/158767926-e98c9204-90a4-4036-83a3-b6c0ec5ffe10.png)
![image](https://user-images.githubusercontent.com/3090191/158768002-e867518a-2db9-4edb-a836-17d56700dd66.png)

**Comment by beetlex-io** [comment]
忘了当时的设计了，内部新建了ServiceCollection并复制了一下，改成这样启动fasthttpapi,在setting方法中注入试一下。
``` csharp
        static void Main(string[] args)
        {
            HttpServer host = new HttpServer(80);
            host.UseTLS("test.pfx", "123456");
            host.Setting((service, option) =>
            {
                service.AddTransient<UserInfo>();
                option.LogToConsole = true;
                option.LogLevel = BeetleX.EventArgs.LogType.Info;
            });
            host.RegisterComponent<Program>();
            host.Run();
        }
```

**Comment by nodyang** [comment]
![image](https://user-images.githubusercontent.com/3090191/158931477-fbcab24d-ac1f-44fc-9f56-ffb9213462d8.png)
![image](https://user-images.githubusercontent.com/3090191/158931503-f92845b5-2bf0-4150-97d7-2d04b86e2593.png)

我测试了一下。连正常的BackgroundService 都起不来。我先用mvc api 顶一下
