### ISSUE TITLE
Options 选项 AllowCredentials 无法设置

### ISSUE THREAD

**Issue by senioi** [beetlex-io/FastHttpApi#174]
public bool? AllowCredentials { get; set; }
![image](https://user-images.githubusercontent.com/42415346/170987627-ea70afb7-c8a8-473f-9c4a-421ad6951cb2.png)

**Comment by beetlex-io** [comment]
真没想到不支持这样编写。。。

**Comment by beetlex-io** [comment]
更新到 2.2.16.1803  属性改成string

**Comment by beetlex-io** [comment]
已更新
