### ISSUE TITLE
请问这类错误怎么排查: <send data completed error>

### ISSUE THREAD

**Issue by senioi** [beetlex-io/FastHttpApi#176]
完全没头绪,开启debug也不显示详细,
返回也是申明了类型,也没有null返回,
请问这个错误是超时嘛?
![image](https://user-images.githubusercontent.com/42415346/173182943-87600126-46be-4ac2-a1f5-41a139cfaa05.png)

**Comment by beetlex-io** [comment]
这种情况是数据发送完成后，连接被关闭，组件在处理后续工作时已经无法找到已释放会话。
