### ISSUE TITLE
大佬，为什么接收消息之后，buffer不释放

### ISSUE THREAD

**Issue by Kornephoros** [beetlex-io/FastHttpApi#180]
![image](https://user-images.githubusercontent.com/57654644/183794270-4d44c3fc-6ef8-4016-a75c-49c3b0e684d3.png)
![image](https://user-images.githubusercontent.com/57654644/183794372-a7caa9dd-b581-41cc-a09a-19728fa823a5.png)
这边的几百个byte[]大小都和设置里面的BufferSize一样。在服务器接收的消息多了之后，会占用大量内存，直至把服务器内存撑爆。

**Comment by beetlex-io** [comment]
buffer分配总容量不会超过BufferPoolMaxMemroy超过再分配就抛异常；buffer会常住一定数量并不会回收，这是组件的设计机制。

**Comment by Kornephoros** [comment]
buffer不回收是为了速度考虑吗。如果bufferPoolMaxMemory被超过了，需要怎么处理呢。旧的buffer不会重复利用吗

**Comment by beetlex-io** [comment]
不存在旧的buffer,buffer在pool中是重复使用的，也有个别没标记回收的会定时清除。其实buffer size 8k就行没有必要定义这么大
